apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: mtuci-eda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: mtuci-eda/notification:latest
          ports:
            - containerPort: 8005
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8005
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8005
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: mtuci-eda
spec:
  selector:
    app: notification
  ports:
    - port: 80
      targetPort: 8005


