apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: mtuci-eda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: mtuci-eda/order:latest
          ports:
            - containerPort: 8003
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8003
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8003
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: mtuci-eda
spec:
  selector:
    app: order
  ports:
    - port: 80
      targetPort: 8003


