apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant
  namespace: mtuci-eda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant
  template:
    metadata:
      labels:
        app: restaurant
    spec:
      containers:
        - name: restaurant
          image: mtuci-eda/restaurant:latest
          ports:
            - containerPort: 8004
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8004
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8004
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant
  namespace: mtuci-eda
spec:
  selector:
    app: restaurant
  ports:
    - port: 80
      targetPort: 8004


