apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: mtuci-eda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: mtuci-eda/user:latest
          ports:
            - containerPort: 8002
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: mtuci-eda
spec:
  selector:
    app: user
  ports:
    - port: 80
      targetPort: 8002


